## Real estate data cleaning with Pandas for efficient analysis
This is a real dataset that was downloaded using web scraping techniques. The data contains records from Fotocasa, one of the most popular real estate websites in Spain. Please do not perform web scraping unless it is for academic purposes.

The dataset was downloaded a few years ago by Henry Navarro, and no economic benefit was obtained from it.

It contains thousands of real house listings published on the website www.fotocasa.com. Your goal is to extract as much information as possible with the data science knowledge you have acquired so far.

Let's get started!

- First, let's read and explore the dataset.

In [1]:
# Step 0. Load libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Step 1. Load data
df_raw = pd.read_csv("../real_estate.csv",sep=";")
df_raw.sample(10)

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level4Id,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone
3715,3716,149109553,False,avance urbano,949801032.0,https://www.fotocasa.es/es/comprar/vivienda/mo...,3.0,3.0,130.0,188000,...,0,0,0,0,0,0,"40,5451131547012","-3,33450767059326",NaN,NaN
5916,5917,153348111,False,aproperties,914890879.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,2.0,149.0,795000,...,0,0,0,0,0,0,"40,41731","-3,67478",NaN,NaN
1376,1377,153308040,False,vilsa grupo inmobiliario,912172763.0,https://www.fotocasa.es/es/comprar/vivienda/sa...,NaN,NaN,128.0,162000,...,0,0,0,0,0,0,"40,2995445864376","-3,43876471356237",NaN,NaN
610,611,152555693,False,facilidades de casas,910301692.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,97.0,115000,...,0,0,0,0,0,0,"40,4764","-3,38614",NaN,NaN
1035,1036,154000682,True,oih,912170482.0,https://www.fotocasa.es/es/comprar/vivienda/me...,1.0,1.0,41.0,190000,...,0,0,0,0,0,0,"40,4088485786438","-3,69888857864376",NaN,NaN
9860,9861,152285878,False,don piso,912664498.0,https://www.fotocasa.es/es/comprar/vivienda/co...,2.0,2.0,63.0,505000,...,0,0,0,0,0,0,"40,421595","-3,674355",NaN,NaN
6532,6533,152274780,False,housell,914873928.0,https://www.fotocasa.es/es/comprar/vivienda/to...,5.0,3.0,205.0,176999,...,0,0,0,0,0,0,"40,0653333","-3,4914731",NaN,NaN
9383,9384,153438283,False,gilmar aravaca,912788012.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,206.0,753000,...,0,0,0,0,0,0,"40,4627407","-3,7973625",NaN,NaN
6529,6530,150834849,False,solvia inmobiliaria,932933810.0,https://www.fotocasa.es/es/comprar/vivienda/to...,4.0,2.0,115.0,292200,...,0,0,0,0,0,1,"40,3479833","-3,7025694",NaN,NaN
13095,13096,153599035,False,colmehogar,918007163.0,https://www.fotocasa.es/es/comprar/vivienda/vi...,4.0,2.0,90.0,212428,...,0,0,0,0,0,0,"40,57536","-4,00566",NaN,NaN

In [3]:
# Step 2. See info
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15335 entries, 0 to 15334
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        15335 non-null  int64
 1   id_realEstates    15335 non-null  int64
 2   isNew             15335 non-null  bool
 3   realEstate_name   15325 non-null  object
 4   phone_realEstate  14541 non-null  float64
 5   url_inmueble      15335 non-null  object
 6   rooms             14982 non-null  float64
 7   bathrooms         14990 non-null  float64
 8   surface           14085 non-null  float64
 9   price             15335 non-null  int64
 10  date              15335 non-null  object
 11  description       15193 non-null  object
 12  address           15335 non-null  object
 13  country           15335 non-null  object
 14  level1            15335 non-null  object
 15  level2            15335 non-null  object
 16  level3            15335 non-null  object
 17  level4            8692 non-null   object
 18  level5            15335 non-null  object
 19  level6            708 non-null    object
 20  level7            13058 non-null  object
 21  level8            6756 non-null   object
 22  upperLevel        15335 non-null  object
 23  countryId         15335 non-null  int64
 24  level1Id          15335 non-null  int64
 25  level2Id          15335 non-null  int64
 26  level3Id          15335 non-null  int64
 27  level4Id          15335 non-null  int64
 28  level5Id          15335 non-null  int64
 29  level6Id          15335 non-null  int64
 30  level7Id          15335 non-null  int64
 31  level8Id          15335 non-null  int64
 32  accuracy          15335 non-null  int64
 33  latitude          15335 non-null  object
 34  longitude         15335 non-null  object
 35  zipCode           0 non-null      float64
 36  customZone        0 non-null      float64
dtypes: bool(1), float64(6), int64(13), object(17)
memory usage: 4.2+ MB

In [ ]:
#Step 3. Preprossesing
df_baking = df_raw.copy()
df_baking = df_baking.iloc[:,1:-2]
df_baking["date"] = pd.to_datetime(df_baking["date"],errors="coerce")
df_baking.columns = df_baking.columns.str.lower()
df_baking = df_baking.drop(columns=["country","countryid","level1id","level2id","level3id","level4id","level5id","level6id","level7id","level8id","accuracy"])
df_baking["id_realestates"] = df_baking["id_realestates"].astype("category")
df_baking["phone_realestate"] = df_baking["phone_realestate"].astype("category")
df_baking["realestate_name"] = df_baking["realestate_name"].astype("category")
df_baking["url_inmueble"] = df_baking["url_inmueble"].astype("category")
df_baking["address"] = df_baking["address"].astype("category")
df_baking["description"] = df_baking["description"].astype("category")
df_baking["latitude"] = df_baking["latitude"].str.replace(",",".")
df_baking["latitude"] = df_baking["latitude"].astype(float)
df_baking["longitude"] = df_baking["longitude"].str.replace(",",".")
df_baking["longitude"] = df_baking["longitude"].astype(float)
df_baking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15335 entries, 0 to 15334
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_realestates    15335 non-null  category
 1   isnew             15335 non-null  bool
 2   realestate_name   15325 non-null  category
 3   phone_realestate  14541 non-null  category
 4   url_inmueble      15335 non-null  category
 5   rooms             14982 non-null  float64
 6   bathrooms         14990 non-null  float64
 7   surface           14085 non-null  float64
 8   price             15335 non-null  int64
 9   date              683 non-null    datetime64[ns, UTC]
 10  description       15193 non-null  category
 11  address           15335 non-null  category
 12  level1            15335 non-null  object
 13  level2            15335 non-null  object
 14  level3            15335 non-null  object
 15  level4            8692 non-null   object
 16  level5            15335 non-null  object
 17  level6            708 non-null    object
 18  level7            13058 non-null  object
 19  level8            6756 non-null   object
 20  upperlevel        15335 non-null  object
 21  latitude          15335 non-null  float64
 22  longitude         15335 non-null  float64
dtypes: bool(1), category(6), datetime64[ns, UTC](1), float64(5), int64(1), object(9)
memory usage: 3.4+ MB

15335

In [ ]:
#lista
my_list = [1,2,3,4,5,5]
my_list
my_list[0]
my_list[-3] #de atras para adelante
my_list[0] = 5 #repetibles y mutables

In [ ]:
my_tuple = (5.5,2,3,4,5)
#my_tuple[0] = 2 #error

In [ ]:
my_dic = {
    "age":10,
    "name":"Joe" ,
    "list": [1,2,3]
}
my_dic["name"]

'Joe'

In [ ]:
my_10df = pd.DataFrame({
    "name":["Joe","Jack","Jane"],
    "age":[24,25,26]
})
my_10df

   name  age
0   Joe   24
1  Jack   25
2  Jane   26

In [ ]:
df_baking['rooms'] #Serie
df_baking[['rooms']] #DataFrame
display(df_baking['rooms'].min())
display(df_baking['rooms'].max())
display(df_baking['rooms'].mean())
display(df_baking['rooms'].describe())
df_baking['rooms'].isna().sum()
#df_baking[['rooms',"bathrooms"]] #df

np.float64(1.0)

np.float64(30.0)

np.float64(3.2316112668535575)

count    14982.000000
mean         3.231611
std          1.393106
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max         30.000000
Name: rooms, dtype: float64

np.int64(353)

In [ ]:
display(df_baking['rooms'].isna().sum()/df_baking.shape[0])

np.float64(0.023019237039452235)

In [ ]:
df_baking[["rooms","bathrooms"]].min()
df_baking[["rooms","bathrooms"]].max()
# df_baking.describe().T
#df_baking.describe(include="all")
df_baking.describe(include="category")

,id_realestates,isnew,realestate_name,phone_realestate,url_inmueble,rooms,bathrooms,surface,price,date,...,level2,level3,level4,level5,level6,level7,level8,upperlevel,latitude,longitude
count,15335.0,15335,15325,14541.0,15335,14982.000000,14990.000000,14085.000000,1.533500e+04,683,...,15335,15335,8692,15335,708,13058,6756,15335,15335,15335
unique,14217.0,2,1821,1807.0,493,NaN,NaN,NaN,NaN,NaN,...,1,7,77,168,19,247,143,512,10865,10734
top,150803398.0,False,engel volkers madrid,910758015.0,https://www.fotocasa.es/es/comprar/vivienda/co...,NaN,NaN,NaN,NaN,NaN,...,Madrid,"Madrid, Zona de","Alcalá de Henares, Zona de",Madrid Capital,San Sebastián de los Reyes - ciudad,Centro,Universidad - Malasaña,Centro,"40,4980556","-3,3755556"
freq,3.0,15198,470,470.0,90,NaN,NaN,NaN,NaN,NaN,...,15335,6643,525,6643,168,1474,206,760,114,114
mean,NaN,NaN,NaN,NaN,NaN,3.231611,2.150233,196.916436,4.773036e+05,2019-12-28 18:51:42.703134464+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,15.000000,0.000000e+00,2019-12-28 18:27:15.968054700+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,2.000000,1.000000,80.000000,1.690000e+05,2019-12-28 18:36:34.207266304+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,3.000000,2.000000,114.000000,2.800000e+05,2019-12-28 18:50:22.766116096+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,4.000000,3.000000,205.000000,5.400000e+05,2019-12-28 19:07:31.090020096+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,30.000000,20.000000,249000.000000,8.500000e+06,2019-12-28 19:18:02.688162200+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,1.393106,1.292079,2182.758313,5.912942e+05,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df_baking[df_baking["realestate_name"] == 'engel volkers madrid']
df_baking[df_baking["bathrooms"] > 10]
df_baking[df_baking["price"] < 10]

,id_realestates,isnew,realestate_name,phone_realestate,url_inmueble,rooms,bathrooms,surface,price,date,...,level2,level3,level4,level5,level6,level7,level8,upperlevel,latitude,longitude
366,153637952,False,esalje,912786497.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,4.0,262.0,0,2019-12-28 18:52:25.965658+00:00,...,Madrid,Zona Sur de Madrid,"Parla, Zona de",Parla,NaN,Fuentebella - El Nido,NaN,Fuentebella - El Nido,40.232020,-3.781320
694,151796397,False,kiboko,914891538.0,https://www.fotocasa.es/vivienda/san-sebastian...,1.0,1.0,42.0,0,NaT,...,Madrid,Zona Norte de Madrid,"San Sebastián de los Reyes, Zona de",San Sebastián de los Reyes,San Sebastián de los Reyes - ciudad,Polígono Industrial Sur,NaN,Polígono Industrial Sur,40.556089,-3.611072
1003,154000828,True,cr homes,914890664.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,104.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Getafe, Zona de",Getafe,NaN,Los Molinos,NaN,Los Molinos,40.315273,-3.705733
1255,153129697,False,montebalito madrid,911226374.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,6.0,6.0,299.0,0,NaT,...,Madrid,"Madrid, Zona de",NaN,Madrid Capital,NaN,Fuencarral,Peñagrande,Peñagrande,40.477110,-3.732450
1534,151708345,False,living gestion de proyectos,911221479.0,https://www.fotocasa.es/vivienda/pozuelo-de-al...,2.0,1.0,75.0,0,NaT,...,Madrid,Zona Noroeste,"Pozuelo de Alarcón, Zona de",Pozuelo de Alarcón,NaN,NaN,NaN,Pozuelo de Alarcón,40.433819,-3.817579
1554,151469598,False,hi real estate,911367572.0,https://www.fotocasa.es/vivienda/madrid-capita...,4.0,3.0,334.0,0,NaT,...,Madrid,Zona Noroeste,"Boadilla del Monte, Zona de",Boadilla del Monte,NaN,Sector B,NaN,Sector B,40.412827,-3.918518
1645,149639018,False,viviendas para ti,918003243.0,https://www.fotocasa.es/es/comprar/vivienda/ci...,2.0,2.0,131.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Getafe, Zona de",Getafe,NaN,Centro,NaN,Centro,40.307540,-3.728690
1798,142524805,False,cyopsa sisocia,910751523.0,https://www.fotocasa.es/vivienda/arroyomolinos...,2.0,2.0,89.0,0,NaT,...,Madrid,"Madrid, Zona de",NaN,Madrid Capital,NaN,Tetuán,Almenara -Ventilla,Almenara -Ventilla,40.471410,-3.698030
1829,142524805,False,cyopsa sisocia,910751523.0,https://www.fotocasa.es/vivienda/madrid-capita...,2.0,2.0,89.0,0,NaT,...,Madrid,"Madrid, Zona de",NaN,Madrid Capital,NaN,Tetuán,Almenara -Ventilla,Almenara -Ventilla,40.471410,-3.698030
2049,146493640,False,majhol,910752183.0,https://www.fotocasa.es/es/comprar/vivienda/ar...,3.0,3.0,139.0,0,NaT,...,Madrid,Zona Suroeste,"Móstoles, Zona de",Móstoles,NaN,Sur - PAU 4,NaN,Sur - PAU 4,40.306700,-3.858970
2058,149127826,False,en casa proyectos,918003046.0,https://www.fotocasa.es/es/comprar/vivienda/ar...,6.0,5.0,350.0,0,NaT,...,Madrid,Zona Noroeste,"Majadahonda, Zona de",Majadahonda,NaN,Zona Carretera del Plantío,NaN,Zona Carretera del Plantío,40.471440,-3.856120
2197,153930054,False,torrecerredo,911228329.0,https://www.fotocasa.es/vivienda/aranjuez/terr...,3.0,2.0,104.0,0,NaT,...,Madrid,Zona Noroeste,"Villanueva del Pardillo, Zona de",Villanueva del Pardillo,NaN,Ibiza - San Pedro,NaN,Ibiza - San Pedro,40.487379,-3.962651
2266,150007098,False,construcciones juan redondo,912780568.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,3.0,150.0,0,NaT,...,Madrid,Zona Sur de Madrid,Resto poblaciones A4,Torrejón de la Calzada,NaN,NaN,NaN,Torrejón de la Calzada,40.204319,-3.804759
2750,153847527,False,donpiso pozuelo,912179723.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,5.0,3.0,330.0,0,NaT,...,Madrid,"Madrid, Zona de",NaN,Madrid Capital,NaN,Salamanca,Recoletos,Recoletos,40.421630,-3.682620
3036,153170335,False,comercial,910302598.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,1.0,67.0,0,NaT,...,Madrid,"Madrid, Zona de",NaN,Madrid Capital,NaN,Chamartín,Prosperidad,Prosperidad,40.446930,-3.663440
3201,153807749,False,lideco asesores,912780819.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,80.0,0,NaT,...,Madrid,Corredor del Henares,"Torrejón de Ardoz, Zona de",Torrejón de Ardoz,NaN,Parque Cataluña - Cañada - Soto,NaN,Parque Cataluña - Cañada - Soto,40.457185,-3.451974
3435,153993957,False,redpiso vallecas madrid sur,910757640.0,https://www.fotocasa.es/es/comprar/vivienda/to...,2.0,1.0,68.0,0,NaT,...,Madrid,"Madrid, Zona de",NaN,Madrid Capital,NaN,Puente de Vallecas,Palomeras Bajas,Palomeras Bajas,40.382864,-3.658950
3959,149638965,False,viviendas para ti,918003243.0,https://www.fotocasa.es/es/comprar/vivienda/ar...,3.0,2.0,141.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Getafe, Zona de",Getafe,NaN,Centro,NaN,Centro,40.307540,-3.728690
3989,149638965,False,viviendas para ti,918003243.0,https://www.fotocasa.es/es/comprar/vivienda/ar...,3.0,2.0,141.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Getafe, Zona de",Getafe,NaN,Centro,NaN,Centro,40.307540,-3.728690
4019,149638965,False,viviendas para ti,918003243.0,https://www.fotocasa.es/es/comprar/vivienda/ar...,3.0,2.0,141.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Getafe, Zona de",Getafe,NaN,Centro,NaN,Centro,40.307540,-3.728690
4031,151708316,False,living gestion de proyectos,911221479.0,https://www.fotocasa.es/vivienda/alcobendas/al...,2.0,2.0,80.0,0,NaT,...,Madrid,Zona Noroeste,"Pozuelo de Alarcón, Zona de",Pozuelo de Alarcón,NaN,NaN,NaN,Pozuelo de Alarcón,40.434160,-3.817720
4167,146493649,False,majhol,910752183.0,https://www.fotocasa.es/vivienda/madrid-capita...,4.0,3.0,139.0,0,NaT,...,Madrid,Zona Suroeste,"Móstoles, Zona de",Móstoles,NaN,Sur - PAU 4,NaN,Sur - PAU 4,40.306300,-3.858970
4362,149638983,False,viviendas para ti,918003243.0,https://www.fotocasa.es/es/comprar/vivienda/ri...,2.0,2.0,141.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Getafe, Zona de",Getafe,NaN,Centro,NaN,Centro,40.307540,-3.728690
4605,153929839,False,torrecerredo,911228329.0,https://www.fotocasa.es/es/comprar/vivienda/nu...,2.0,2.0,81.0,0,NaT,...,Madrid,Zona Noroeste,"Villanueva del Pardillo, Zona de",Villanueva del Pardillo,NaN,Ibiza - San Pedro,NaN,Ibiza - San Pedro,40.487320,-3.962510
4902,153991263,False,premium consultores asesores,916353096.0,https://www.fotocasa.es/es/comprar/vivienda/me...,1.0,1.0,48.0,0,NaT,...,Madrid,"Madrid, Zona de",NaN,Madrid Capital,NaN,Puente de Vallecas,San Diego,San Diego,40.395600,-3.669580
5013,153990577,False,particular,NaN,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,NaN,NaN,0,NaT,...,Madrid,Zona Suroeste,"Arroyomolinos, Zona de",Arroyomolinos (Madrid),NaN,Zona Bulevar y Europa,NaN,Zona Bulevar y Europa,40.278520,-3.923720
5072,139815777,False,edicasa inmobiliaria,911797025.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,NaN,NaN,80.0,0,NaT,...,Madrid,Corredor del Henares,"Torrejón de Ardoz, Zona de",Torrejón de Ardoz,NaN,Centro,NaN,Centro,40.460070,-3.478180
5439,149778247,False,promotasa,914894395.0,https://www.fotocasa.es/es/comprar/vivienda/cu...,5.0,3.0,340.0,0,NaT,...,Madrid,Madrid Sureste - Cuenca Tajuña,"Rivas-Vaciamadrid, Zona de",Rivas-vaciamadrid,NaN,Centro,NaN,Centro,40.350380,-3.516190
5446,153153518,False,promotasa,914894395.0,https://www.fotocasa.es/es/comprar/vivienda/cu...,2.0,2.0,97.0,0,NaT,...,Madrid,"Madrid, Zona de",NaN,Madrid Capital,NaN,San Blas,Rejas,Rejas,40.443236,-3.592392
5463,149193466,False,gm gestion inmobiliaria,910756085.0,https://www.fotocasa.es/es/comprar/vivienda/cu...,4.0,3.0,274.0,0,NaT,...,Madrid,Corredor del Henares,"Camarma de Esteruelas, Zona de",Camarma de Esteruelas,NaN,NaN,NaN,Camarma de Esteruelas,40.550180,-3.376090
5628,153985829,False,msm gestion inmobiliaria,912785063.0,https://www.fotocasa.es/es/comprar/vivienda/na...,4.0,3.0,226.0,0,NaT,...,Madrid,Zona Sur de Madrid,Resto poblaciones A4,Moraleja de Enmedio,NaN,NaN,NaN,Moraleja de Enmedio,40.264190,-3.859980
5645,153717864,False,lideco asesores,912788076.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,118.0,0,NaT,...,Madrid,Corredor del Henares,"Torrejón de Ardoz, Zona de",Torrejón de Ardoz,NaN,Parque Cataluña - Cañada - Soto,NaN,Parque Cataluña - Cañada - Soto,40.441559,-3.461456
5648,153585814,False,lideco asesores,912788076.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,115.0,0,NaT,...,Madrid,Corredor del Henares,"Torrejón de Ardoz, Zona de",Torrejón de Ardoz,NaN,Veredillas - Juncal - Zarzuela,NaN,Veredillas - Juncal - Zarzuela,40.456420,-3.472154
6439,149639083,False,viviendas para ti,918003243.0,https://www.fotocasa.es/es/comprar/vivienda/vi...,2.0,2.0,115.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Getafe, Zona de",Getafe,NaN,Centro,NaN,Centro,40.307540,-3.728690
6585,151000047,False,living gestion de proyectos,911221479.0,https://www.fotocasa.es/vivienda/madrid-capita...,3.0,2.0,185.0,0,NaT,...,Madrid,Zona Noroeste,"Pozuelo de Alarcón, Zona de",Pozuelo de Alarcón,NaN,NaN,NaN,Pozuelo de Alarcón,40.434160,-3.817720
7227,149639061,False,viviendas para ti,918003243.0,https://www.fotocasa.es/es/comprar/vivienda/co...,2.0,2.0,120.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Getafe, Zona de",Getafe,NaN,Centro,NaN,Centro,40.307540,-3.728690
7331,150999812,False,living gestion de proyectos,911221479.0,https://www.fotocasa.es/es/comprar/vivienda/mo...,4.0,3.0,136.0,0,NaT,...,Madrid,Zona Noroeste,"Pozuelo de Alarcón, Zona de",Pozuelo de Alarcón,NaN,NaN,NaN,Pozuelo de Alarcón,40.434160,-3.817720
7356,149639033,False,viviendas para ti,918003243.0,https://www.fotocasa.es/vivienda/madrid-capita...,3.0,2.0,120.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Getafe, Zona de",Getafe,NaN,Centro,NaN,Centro,40.307540,-3.728690
8111,153901156,False,angeles,NaN,https://www.fotocasa.es/es/comprar/vivienda/ma...,1.0,1.0,NaN,0,NaT,...,Madrid,Zona Suroeste,"Brunete, Zona de",Brunete,NaN,NaN,NaN,Brunete,40.406130,-3.993800
8172,150999741,False,living gestion de proyectos,911221479.0,https://www.fotocasa.es/vivienda/rivas-vaciama...,2.0,1.0,87.0,0,NaT,...,Madrid,Zona Noroeste,"Pozuelo de Alarcón, Zona de",Pozuelo de Alarcón,NaN,NaN,NaN,Pozuelo de Alarcón,40.434160,-3.817720
8183,151796409,False,kiboko,914891538.0,https://www.fotocasa.es/vivienda/rivas-vaciama...,2.0,1.0,65.0,0,NaT,...,Madrid,Zona Norte de Madrid,"San Sebastián de los Reyes, Zona de",San Sebastián de los Reyes,San Sebastián de los Reyes - ciudad,Polígono Industrial Sur,NaN,Polígono Industrial Sur,40.556089,-3.611072
8192,149639078,False,viviendas para ti,918003243.0,https://www.fotocasa.es/vivienda/rivas-vaciama...,2.0,2.0,115.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Getafe, Zona de",Getafe,NaN,Centro,NaN,Centro,40.307540,-3.728690
8256,149639057,False,viviendas para ti,918003243.0,https://www.fotocasa.es/vivienda/madrid-capita...,2.0,2.0,120.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Getafe, Zona de",Getafe,NaN,Centro,NaN,Centro,40.307540,-3.728690
8828,153967163,False,inmocasa mostoles,911224049.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,73.0,0,NaT,...,Madrid,Zona Suroeste,"Móstoles, Zona de",Móstoles,NaN,Centro,NaN,Centro,40.319252,-3.859932
8962,153122164,False,msm gestion inmobiliaria,912785063.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,4.0,427.0,0,NaT,...,Madrid,Zona Noroeste,"El Escorial, Zona de",El Escorial,NaN,Navalquejigo - Los Arroyos,NaN,Navalquejigo - Los Arroyos,40.594620,-4.042610
10292,151594848,False,centro comercial inmobiliario 10,912188593.0,https://www.fotocasa.es/es/comprar/vivienda/to...,2.0,2.0,100.0,0,NaT,...,Madrid,Corredor del Henares,"Coslada, Zona de",Coslada,NaN,Pueblo – Barrio del Puerto,NaN,Pueblo – Barrio del Puerto,40.417149,-3.572397
10297,153586831,False,asentis,914890774.0,https://www.fotocasa.es/es/comprar/vivienda/fu...,3.0,2.0,143.0,0,NaT,...,Madrid,"Madrid, Zona de",NaN,Madrid Capital,NaN,Villaverde,Butarque,Butarque,40.339840,-3.679020
10436,154002009,True,particular,NaN,https://www.fotocasa.es/es/comprar/vivienda/va...,4.0,3.0,304.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Getafe, Zona de",Getafe,NaN,Sector 3,NaN,Sector 3,40.288660,-3.747460
10498,153958113,False,particular,NaN,https://www.fotocasa.es/es/comprar/vivienda/sa...,3.0,NaN,NaN,0,NaT,...,Madrid,"Madrid, Zona de",NaN,Madrid Capital,NaN,Chamberí,Almagro,Almagro,40.435870,-3.691610
11032,152166181,False,consulting inmobiliario arroyomolinos,912184536.0,https://www.fotocasa.es/es/comprar/vivienda/bo...,NaN,NaN,130.0,0,NaT,...,Madrid,Zona Suroeste,"Arroyomolinos, Zona de",Arroyomolinos (Madrid),NaN,Zona Bulevar y Europa,NaN,Zona Bulevar y Europa,40.279920,-3.917070
11291,151696805,False,gm gestion inmobiliaria,910756085.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,5.0,3.0,330.0,0,NaT,...,Madrid,Corredor del Henares,"Camarma de Esteruelas, Zona de",Camarma de Esteruelas,NaN,NaN,NaN,Camarma de Esteruelas,40.549110,-3.380460
12034,153795120,False,particular,NaN,https://www.fotocasa.es/es/comprar/vivienda/ma...,1.0,NaN,NaN,0,NaT,...,Madrid,"Madrid, Zona de",NaN,Madrid Capital,NaN,Puente de Vallecas,Portazgo,Portazgo,40.394170,-3.647240
12630,153410286,False,outletdeviviendas,912172269.0,https://www.fotocasa.es/es/comprar/vivienda/mi...,NaN,NaN,NaN,0,NaT,...,Madrid,Corredor del Henares,"Villalbilla, Zona de",Corpa,NaN,NaN,NaN,Corpa,40.396046,-3.278024
12667,153942770,False,pqcentro,912665783.0,https://www.fotocasa.es/es/comprar/vivienda/al...,3.0,2.0,89.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Pinto, Zona de",Pinto,NaN,La Tenería I – La Tenería II,NaN,La Tenería I – La Tenería II,40.258520,-3.702810
13271,153930505,False,torrecerredo,911228329.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,2.0,155.0,0,NaT,...,Madrid,Zona Noroeste,"Villanueva del Pardillo, Zona de",Villanueva del Pardillo,NaN,Ibiza - San Pedro,NaN,Ibiza - San Pedro,40.487320,-3.962510
13272,153930437,False,torrecerredo,911228329.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,2.0,162.0,0,NaT,...,Madrid,Zona Noroeste,"Villanueva del Pardillo, Zona de",Villanueva del Pardillo,NaN,Ibiza - San Pedro,NaN,Ibiza - San Pedro,40.487320,-3.962510
13273,153275524,False,inmovital,910753408.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,96.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Pinto, Zona de",Pinto,NaN,La Tenería I – La Tenería II,NaN,La Tenería I – La Tenería II,40.257250,-3.699500
14697,153914909,False,basico homes,910757815.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,187.0,0,NaT,...,Madrid,Zona Suroeste,Resto A5,Aldea del Fresno,NaN,NaN,NaN,Aldea del Fresno,40.324000,-4.204290
14773,153914012,False,tecnocasa parla sur y parla este,912185357.0,https://www.fotocasa.es/es/comprar/vivienda/vi...,3.0,2.0,108.0,0,NaT,...,Madrid,Zona Sur de Madrid,"Parla, Zona de",Parla,NaN,Las Américas - Parla Este,NaN,Las Américas - Parla Este,40.223320,-3.754920
15204,153904931,False,premium consultores asesores,916353096.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,6.0,11.0,1499.0,0,NaT,...,Madrid,Zona Norte de Madrid,"Alcobendas, Zona de",Alcobendas,La Moraleja,La Moraleja distrito,NaN,La Moraleja distrito,40.522370,-3.610440

In [18]:
df_baking["price"].mean()

np.float64(477303.56641669385)

In [20]:
df_baking[df_baking["price"] != 0]["price"].mean()
df_baking[df_baking["price"] != 0]["price"].median()

np.float64(282048.0)

In [22]:
df_baking[(df_baking["price"] != 0) & (df_baking["price"] < 282000)]["price"].mean()

np.float64(174570.37863695936)